### ISSUE TITLE
Create issue checklists

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#174]
As discussed in #171, we should create checklists for issues similar to the ones we have for PRs.

It would be nice to have the following templates:

- Bug Report
- Question
- Release

**Comment by JuliaKukulies** [comment]
Just a reminder to us that the version bump for releases has to be done in `__init__.py` instead of `setup.py` when #175 is merged and that the current release check list (as in  #171) needs at least two additional points: 

- [ ] Merge `Hotfix` or `RC_v.x` into other dev branch/es ( i.e. `RC_v1.minor` and  `RC_v1.major`) 
- [ ] If release was a hotfix, delete `Hotfix` branch


And are we directly updating the RC branch name after a release, for example `RC_v1.4.0` -> `RC_v1.6.0`  when `RC_v1.4.0` will be merged into `main` or are we waiting until we plan the next versions?

**Comment by fsenf** [comment]
We adapted the checklist approach for tobac-tutorials. With all the additions we needed to include w.r.t. data upload and sphinx checks, it really felt overwhelming ... so, we tried to make it a bit more structured including a questionnaire for the descriptive part of the PR.

See here: https://github.com/tobac-project/tobac-tutorials/issues/15  & https://github.com/tobac-project/tobac-tutorials/pull/18/files

@freemansw1 & @JuliaKukulies : What is your opinion? Should also update our tobac PR template in a similar way?

**Comment by freemansw1** [comment]
I think the template in tobac-tutorials is a good one, and switching our templates to be more like that is a good idea in my mind.

**Comment by JuliaKukulies** [comment]
I agree @fsenf, I think your idea to have structured subsections is very good to make templates easier to read

**Comment by w-k-jones** [comment]
Resolved with #358
