### ISSUE TITLE
Need `dxy` parameter in `feature_detection_multithreshold`

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#194]
I came across this while working on #127: the `feature_detection.feature_detection_multithreshold` function (which most users will be using for feature detection) is missing the `dxy` parameter in RC_v1.4.0:

https://github.com/tobac-project/tobac/blob/29e55984248b2a1dfb2205834dd3df0e2ad9a7a3/tobac/feature_detection.py#L535

**Comment by JuliaKukulies** [comment]
Hm, I am slightly confused @freemansw1. When I look at `feature_detection_multithreshold()` in `feature_detection.py` for `RC_v1.4.0` I can see the `dxy` parameter. I can see that you have noticed this after merging `RC_v1.5.0` into your `dev-3D-PBC` branch but I do not understand where it comes from since `dev` also contains `dxy` `feature_detection_multithreshold()`. 

This may be a good reminder to us to add `feature_detection_multithreshold()` in the unit tests because this is like you say the function that most users will be using in the end.

**Comment by freemansw1** [comment]
You are totally right, @JuliaKukulies . I had completely missed it when merging in because it's at the top/is not a keyword argument. My apologies!
