### ISSUE TITLE
Add ability to only detect feature if previous `n_min_threshold` is met

### ISSUE THREAD

**Issue by freemansw1** [tobac-project/tobac#261]
From the tobac tutorial today - if you set multiple `n_min_threshold` values with multiple `threshold` values, each is treated independently. For example, for `n_min_threshold = [100, 4]`, if the second n_min_threshold is met but not the first, the next feature is still detected. We should probably have an option to force detection of less extreme threshold values.

**Comment by lettlini** [comment]
I can have a look into that. Do I understand this correctly: you suggest that we add an option that requires a parent feature to be present for the `i`th threshold value in order for a feature to be detected at the `i+1`th threshold value (`i` > 1)?

**Comment by JuliaKukulies** [comment]
That is a good point and I completely agree that we should an option to force the detection of less extreme thresholds. The question is only if this option would force all previous thresholds to be met or if this option can be specified for each of the thresholds? 

Thanks @lettlini for looking into that! Let me know if you have any questions with regard to the current implementation of multiple `n_min_thresholds` (see #208).

**Comment by lettlini** [comment]
I have just created a draft PR with the basic functionality implemented. I still need to add adequate unit tests and integrate the new keyword argument into the higher level functions that call `feature_detection_multithreshold_timestep`. 

Nevertheless, I would like to ask you already now for your opinions and comments on the underlying methodology.

**Comment by JuliaKukulies** [comment]
Thanks for already working on this @lettlini! I just had a look. If I understand it correctly, your implementation simply ends the feature detection when the last threshold was not met, but makes sure to also remove areas outside of the detected features in each iteration so that the next (more extreme) threshold must lie within the region of the previously detected features. I think this implementation is clever! And we do probably not need the option to define `strict_thresholding` for each threshold as it is not a common use case. When users want a mix of both, they can just run the feature detection multiple times.

**Comment by JuliaKukulies** [comment]
@lettlini, just a note as you are working on the PR: It would be great if you could also update the example https://tobac.readthedocs.io/en/latest/feature_detection/notebooks/n_min_threshold_example.html on the RTD page and briefly explain the effect of `strict_thresholding = True`

**Comment by lettlini** [comment]
Thanks for the hint, I will do that!

**Comment by freemansw1** [comment]
Closing this since #283 has been merged
