### ISSUE TITLE
`iris`/`numpy` incomptibility causing notebook issues

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#294]
Another annoying dependency issue...

`iris v3.6.0` is incompatible with the latest version of `numpy` (`v1.24.3`) https://github.com/SciTools/iris/pull/5274

When creating a new environment with `mamba`, it prioritises `numpy v1.24.3` and installs an older version of `iris`, `v3.1.0`

This version of `iris.load_cube` causes an error if given a `pathlib.Path` object to load, which causes the notebooks to fail

I expect this isn't causing an error in the notebook tests because we use `conda` to create the environment there, and it probably solves in a different way.

Short term can be fixed by casting the file paths to strings

**Comment by JuliaKukulies** [comment]
Oh no, how annoying. But great that you figured that out so quickly. I believe we can just go back to casting strings as these work in any case and any version of iris (and xarray) which probably outweighs the advantages of making use of `pathlib.Path` objects :) 

 Are you planning to fix this for `v1.5.0` ?

**Comment by freemansw1** [comment]
Screaming internally right now. Iris somehow finding a way to irritate me yet again. 

It would probably be better to fix this for v1.5, especially since the short-term fix seems reasonable. 

As an aside, the other issue raised in the PR around NetCDF incompatibilities that Will raised above *will* likely cause us (and many other libraries) headaches in the future. I've already experienced some of this with the newer `libnetcdf` libraries requiring `libjpeg-turbo` instead of `jpeg`, which can cause cascading incompatibilities.

**Comment by w-k-jones** [comment]
Yes, I resisted the urge to include "long term solution is to yeet `iris` into the sun" in the original issue...

I'll put together a quick PR this week to fix this, also allows me to fix an issue I found with the changes I made to the requirements files!

The switch to `xarray` should hopefully cut down our web of dependencies quite a bit and limit these kinds of issues. I'd rather avoid having to start pinning packages in the requirements

**Comment by JuliaKukulies** [comment]
Holy moly @freemansw1 NETCDF4 incompabilities are really no joke, I have also experienced some of these. We'll have to keep an eye on this. 

Thanks for fixing the strings @w-k-jones !

**Comment by freemansw1** [comment]
Resolved with #295
