### ISSUE TITLE
Clarify use of thresholds in documentation 

### ISSUE THREAD

**Issue by JuliaKukulies** [tobac-project/tobac#346]
Currently, we use the thresholds for feature detection in an inclusive way (mask is created based on `data >= threshold` or `data<= threshold`), whereas the segmentation is exclusive (e.g., a segmentation mask with a minimum threshold of 241 K will not include any data points == 241 K). 

This is a minor issue, but whenever I start a new tobac project, I have to check the code for this again. I suggest that we just clarify this in our documentation, especially in the docstring description of the threshold values.

**Comment by w-k-jones** [comment]
I did not realise that... maybe we should change it so segmentation is inclusive of the threshold?

**Comment by freemansw1** [comment]
Yeah, this inconsistency isn't great. We should probably long-term change the default so that segmentation is inclusive of the threshold (or vice-versa), but maybe the short-term solution is to update the documentation as @JuliaKukulies proposes and add in a new option to allow inclusivity of the threshold. 

I'm very hesitant to change scientific results without a great deal of warning and an option to keep the original results (for some reasonable period, perhaps a few years).

**Comment by JuliaKukulies** [comment]
I was also a bit worried about how to warn users when we were to change the segmentation code. On the other hand maybe some users already assumed that the segmentation is inclusive but we dont know that for sure. 

Adding the option of inclusivity is maybe a good short-term solution in addition to the documentation clarification, because any documentation changes of our main functions will most likely rather reach new users than old users.
