### ISSUE TITLE
Calculate Bulk Statistics from Raw Data

### ISSUE THREAD

**Issue by John-David-48** [tobac-project/tobac#440]
Could you add the ability to calculate bulk statistics (maximum, mean, etc.) from the raw input data as opposed to tobac's smoothed data?

**Comment by freemansw1** [comment]
@John-David-48 put this in at my request :) . He's meaning on the feature detection module; right now we calculate the bulk statistics on the post-smoothed data rather than the raw data. I think it would be worth doing as an option, but @JuliaKukulies what do you think?

**Comment by JuliaKukulies** [comment]
> @John-David-48 put this in at my request :) . He's meaning on the feature detection module; right now we calculate the bulk statistics on the post-smoothed data rather than the raw data. I think it would be worth doing as an option, but @JuliaKukulies what do you think?

That is a very good point @John-David-48 @freemansw1! I had previously not thought about this since I am not using the smoothing option too much. But yes, I think we should definitely make this possible. I can take care of this. 

@John-David-48 I also want to point out that you can use the postprocessing method to calculate the bulk statistics (`tobac.utils.get_statistics_from_mask`) and give the raw/unsmoothed data as the field to compute the statistics from. I know, it is not the same as for the feature detection method, because this would use the segmented objects rather than the detected features. It is also less efficient, but I just wanted to mention that out in case you were not aware of this option to calculate the statistics from.

**Comment by JuliaKukulies** [comment]
@freemansw1 I have added this to v1.5.4 as of now because I do not think this would be too complicated. Anyhow, as we are getting closer to release the new version I dont want to stop us from this, so in that case we might push this to a later one.

**Comment by JuliaKukulies** [comment]
Hi @John-David-48, 

I have addressed your request and created a pull request for this: #449! Would you be willing to be the third reviewer for that pull request? It would be very helpful if you could test this with your data and see if it works well and gives you the desired result. If this is approved, we will have this new feature release in our next version (`tobac v1.5.4`). 

Let me know what you think!
Julia

**Comment by w-k-jones** [comment]
Resolved by #449
