### ISSUE TITLE
Update black version in check formatting workflow

### ISSUE THREAD

**Issue by w-k-jones** [tobac-project/tobac#453]
Currently, the check formatting workflow uses black version `22.11.0`. This older version is incompatible with python 3.12. However, there are some changes in the way black formats indexing, which means that newer versions of black produce different formatting causing the check to fail. We should update the version used in the check to avoid this becoming more of a problem in future.

**Comment by JuliaKukulies** [comment]
@w-k-jones do you want to change it for the release of `v1.5.4`? It is the reason for  #448 and #449 to currently fail because I used a newer version of `black` for the formatting. I could also just change back to the one that we use in our checks, but then I wonder would the tests still fail because we added `python 3.12` to the matrix testing now?

**Comment by freemansw1** [comment]
This will be resolved by #457

**Comment by freemansw1** [comment]
resolved by #457
