### ISSUE TITLE
Introducing type hints

### ISSUE THREAD

**Issue by mheikenfeld** [tobac-project/tobac#75]
I have made really good experiences with using Python type hints in my recent python projects (similar size and number of contributors our current tobac...). 

It might be a good idea to have a look at it, to make it easier to develop and work with the code, especially when using higher level classes or if we think about packaging some things on our own tobac classes.

For those of you who are not familiar with type hints in Python:  
It basically extends type-agnostic Python  with typing familiar from many other programming languages (but not as strict.)

So an example of a function with type hints (just something stupid  I just made up...) would look like:
```
def some_function(input_data: pd.DataFrame, 
                              column: str,  
                              input_number: float) -> pd.Series:
     series_out=data_in['column']*input_number
     return series_out
```

As far as I understand, it is not enforced by Python when running the code, but helps a lot in development as most IDEs will point you to a wrong type or class while writing code using the function be in with regards to the input or with regards to the return values.
It is obiously in some way a duplication of the info in the docstrings, but in a more applicable way that is directly readable to an IDE

We could also start using it for new additions and then add it to the rest of the code (should be straight forward where there are already the right docstrings ;) )

Any thoughts or experiences?

Some more info:
https://www.python.org/dev/peps/pep-0484/
https://towardsdatascience.com/type-hints-in-python-everything-you-need-to-know-in-5-minutes-24e0bad06d0b

**Comment by freemansw1** [comment]
I think this is a great idea. It certainly does duplicate the docstrings, but updating both shouldn't be much of an issue. My only concern here is that it seems to only work with Python >3.5. I think that's certainly a reasonable version to require (first released in 2015), but just worth noting.

**Comment by mheikenfeld** [comment]
Good point @freemansw1. So we should probably discuss Python version first at some point (might be or get relevant for some other things too after all..) and then think about it, if we agree to require a mininum version >3.5...

**Comment by freemansw1** [comment]
After trying these out on a different project, I'm strongly in favor of us adding these as we can. I do think that we should implement them using the new way (such that e.g., `list[float]` works and we don't need to `from typing import List`). This behavior isn't enabled by default until 3.9, but there's a `from future` import that enables these to work in 3.7. Because of that, I'd be inclined, when we do this, to bump our required version to 3.7 from 3.6. 

I think 1.5 may be a good time to implement that version bump; because of that, I've changed the milestone here to v1.5. We certainly won't have implemented type hints everywhere by then, but it's a good reminder to bump the version.

**Comment by w-k-jones** [comment]
I will close this as type hints have been added to all the major modules. Future development should always include type hints, and update functions to use your hints when modified
